// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	models "gossip/internal/user/model"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockUserRepository is a mock of UserRepository interface.
type MockUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepositoryMockRecorder
}

// MockUserRepositoryMockRecorder is the mock recorder for MockUserRepository.
type MockUserRepositoryMockRecorder struct {
	mock *MockUserRepository
}

// NewMockUserRepository creates a new mock instance.
func NewMockUserRepository(ctrl *gomock.Controller) *MockUserRepository {
	mock := &MockUserRepository{ctrl: ctrl}
	mock.recorder = &MockUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepository) EXPECT() *MockUserRepositoryMockRecorder {
	return m.recorder
}

// ClaimOneTimePreKey mocks base method.
func (m *MockUserRepository) ClaimOneTimePreKey(ctx context.Context, userID uuid.UUID) (*models.OneTimePreKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClaimOneTimePreKey", ctx, userID)
	ret0, _ := ret[0].(*models.OneTimePreKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClaimOneTimePreKey indicates an expected call of ClaimOneTimePreKey.
func (mr *MockUserRepositoryMockRecorder) ClaimOneTimePreKey(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClaimOneTimePreKey", reflect.TypeOf((*MockUserRepository)(nil).ClaimOneTimePreKey), ctx, userID)
}

// CountRemainingOneTimePreKeys mocks base method.
func (m *MockUserRepository) CountRemainingOneTimePreKeys(ctx context.Context, userID uuid.UUID) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountRemainingOneTimePreKeys", ctx, userID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountRemainingOneTimePreKeys indicates an expected call of CountRemainingOneTimePreKeys.
func (mr *MockUserRepositoryMockRecorder) CountRemainingOneTimePreKeys(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountRemainingOneTimePreKeys", reflect.TypeOf((*MockUserRepository)(nil).CountRemainingOneTimePreKeys), ctx, userID)
}

// CreateLoginChallenge mocks base method.
func (m *MockUserRepository) CreateLoginChallenge(ctx context.Context, challenge *models.LoginChallenge) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateLoginChallenge", ctx, challenge)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateLoginChallenge indicates an expected call of CreateLoginChallenge.
func (mr *MockUserRepositoryMockRecorder) CreateLoginChallenge(ctx, challenge interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateLoginChallenge", reflect.TypeOf((*MockUserRepository)(nil).CreateLoginChallenge), ctx, challenge)
}

// CreateUser mocks base method.
func (m *MockUserRepository) CreateUser(ctx context.Context, user *models.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockUserRepositoryMockRecorder) CreateUser(ctx, user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockUserRepository)(nil).CreateUser), ctx, user)
}

// FetchPreKeyBundle mocks base method.
func (m *MockUserRepository) FetchPreKeyBundle(ctx context.Context, userID uuid.UUID) (*models.PreKeyBundle, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchPreKeyBundle", ctx, userID)
	ret0, _ := ret[0].(*models.PreKeyBundle)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchPreKeyBundle indicates an expected call of FetchPreKeyBundle.
func (mr *MockUserRepositoryMockRecorder) FetchPreKeyBundle(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchPreKeyBundle", reflect.TypeOf((*MockUserRepository)(nil).FetchPreKeyBundle), ctx, userID)
}

// FetchPreKeyBundleByUsername mocks base method.
func (m *MockUserRepository) FetchPreKeyBundleByUsername(ctx context.Context, username string) (*models.PreKeyBundle, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchPreKeyBundleByUsername", ctx, username)
	ret0, _ := ret[0].(*models.PreKeyBundle)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchPreKeyBundleByUsername indicates an expected call of FetchPreKeyBundleByUsername.
func (mr *MockUserRepositoryMockRecorder) FetchPreKeyBundleByUsername(ctx, username interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchPreKeyBundleByUsername", reflect.TypeOf((*MockUserRepository)(nil).FetchPreKeyBundleByUsername), ctx, username)
}

// GetIdentityKey mocks base method.
func (m *MockUserRepository) GetIdentityKey(ctx context.Context, userID uuid.UUID) (*models.IdentityKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIdentityKey", ctx, userID)
	ret0, _ := ret[0].(*models.IdentityKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIdentityKey indicates an expected call of GetIdentityKey.
func (mr *MockUserRepositoryMockRecorder) GetIdentityKey(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIdentityKey", reflect.TypeOf((*MockUserRepository)(nil).GetIdentityKey), ctx, userID)
}

// GetIdentityKeyByUsername mocks base method.
func (m *MockUserRepository) GetIdentityKeyByUsername(ctx context.Context, username string) (*models.IdentityKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIdentityKeyByUsername", ctx, username)
	ret0, _ := ret[0].(*models.IdentityKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIdentityKeyByUsername indicates an expected call of GetIdentityKeyByUsername.
func (mr *MockUserRepositoryMockRecorder) GetIdentityKeyByUsername(ctx, username interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIdentityKeyByUsername", reflect.TypeOf((*MockUserRepository)(nil).GetIdentityKeyByUsername), ctx, username)
}

// GetLoginChallenge mocks base method.
func (m *MockUserRepository) GetLoginChallenge(ctx context.Context, challengeID uuid.UUID) (*models.LoginChallenge, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLoginChallenge", ctx, challengeID)
	ret0, _ := ret[0].(*models.LoginChallenge)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLoginChallenge indicates an expected call of GetLoginChallenge.
func (mr *MockUserRepositoryMockRecorder) GetLoginChallenge(ctx, challengeID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLoginChallenge", reflect.TypeOf((*MockUserRepository)(nil).GetLoginChallenge), ctx, challengeID)
}

// GetSignedPreKey mocks base method.
func (m *MockUserRepository) GetSignedPreKey(ctx context.Context, userID uuid.UUID) (*models.SignedPreKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSignedPreKey", ctx, userID)
	ret0, _ := ret[0].(*models.SignedPreKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSignedPreKey indicates an expected call of GetSignedPreKey.
func (mr *MockUserRepositoryMockRecorder) GetSignedPreKey(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSignedPreKey", reflect.TypeOf((*MockUserRepository)(nil).GetSignedPreKey), ctx, userID)
}

// GetUserByID mocks base method.
func (m *MockUserRepository) GetUserByID(ctx context.Context, id uuid.UUID) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByID", ctx, id)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByID indicates an expected call of GetUserByID.
func (mr *MockUserRepositoryMockRecorder) GetUserByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByID", reflect.TypeOf((*MockUserRepository)(nil).GetUserByID), ctx, id)
}

// GetUserByUsername mocks base method.
func (m *MockUserRepository) GetUserByUsername(ctx context.Context, username string) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByUsername", ctx, username)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByUsername indicates an expected call of GetUserByUsername.
func (mr *MockUserRepositoryMockRecorder) GetUserByUsername(ctx, username interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByUsername", reflect.TypeOf((*MockUserRepository)(nil).GetUserByUsername), ctx, username)
}

// MarkChallengeUsed mocks base method.
func (m *MockUserRepository) MarkChallengeUsed(ctx context.Context, challengeID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkChallengeUsed", ctx, challengeID)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkChallengeUsed indicates an expected call of MarkChallengeUsed.
func (mr *MockUserRepositoryMockRecorder) MarkChallengeUsed(ctx, challengeID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkChallengeUsed", reflect.TypeOf((*MockUserRepository)(nil).MarkChallengeUsed), ctx, challengeID)
}

// RegisterUserWithKeys mocks base method.
func (m *MockUserRepository) RegisterUserWithKeys(ctx context.Context, user *models.User, ik *models.IdentityKey, spk *models.SignedPreKey, otpks []models.OneTimePreKey) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterUserWithKeys", ctx, user, ik, spk, otpks)
	ret0, _ := ret[0].(error)
	return ret0
}

// RegisterUserWithKeys indicates an expected call of RegisterUserWithKeys.
func (mr *MockUserRepositoryMockRecorder) RegisterUserWithKeys(ctx, user, ik, spk, otpks interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterUserWithKeys", reflect.TypeOf((*MockUserRepository)(nil).RegisterUserWithKeys), ctx, user, ik, spk, otpks)
}

// SaveIdentityKey mocks base method.
func (m *MockUserRepository) SaveIdentityKey(ctx context.Context, key *models.IdentityKey) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveIdentityKey", ctx, key)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveIdentityKey indicates an expected call of SaveIdentityKey.
func (mr *MockUserRepositoryMockRecorder) SaveIdentityKey(ctx, key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveIdentityKey", reflect.TypeOf((*MockUserRepository)(nil).SaveIdentityKey), ctx, key)
}

// SearchUsersByUsername mocks base method.
func (m *MockUserRepository) SearchUsersByUsername(ctx context.Context, query string, limit int) ([]*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchUsersByUsername", ctx, query, limit)
	ret0, _ := ret[0].([]*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchUsersByUsername indicates an expected call of SearchUsersByUsername.
func (mr *MockUserRepositoryMockRecorder) SearchUsersByUsername(ctx, query, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchUsersByUsername", reflect.TypeOf((*MockUserRepository)(nil).SearchUsersByUsername), ctx, query, limit)
}

// UpdateUserDisplayName mocks base method.
func (m *MockUserRepository) UpdateUserDisplayName(ctx context.Context, userID uuid.UUID, newName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserDisplayName", ctx, userID, newName)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUserDisplayName indicates an expected call of UpdateUserDisplayName.
func (mr *MockUserRepositoryMockRecorder) UpdateUserDisplayName(ctx, userID, newName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserDisplayName", reflect.TypeOf((*MockUserRepository)(nil).UpdateUserDisplayName), ctx, userID, newName)
}

// UploadOneTimePreKeys mocks base method.
func (m *MockUserRepository) UploadOneTimePreKeys(ctx context.Context, userID uuid.UUID, keys []models.OneTimePreKey) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadOneTimePreKeys", ctx, userID, keys)
	ret0, _ := ret[0].(error)
	return ret0
}

// UploadOneTimePreKeys indicates an expected call of UploadOneTimePreKeys.
func (mr *MockUserRepositoryMockRecorder) UploadOneTimePreKeys(ctx, userID, keys interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadOneTimePreKeys", reflect.TypeOf((*MockUserRepository)(nil).UploadOneTimePreKeys), ctx, userID, keys)
}

// UpsertSignedPreKey mocks base method.
func (m *MockUserRepository) UpsertSignedPreKey(ctx context.Context, spk *models.SignedPreKey) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertSignedPreKey", ctx, spk)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertSignedPreKey indicates an expected call of UpsertSignedPreKey.
func (mr *MockUserRepositoryMockRecorder) UpsertSignedPreKey(ctx, spk interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertSignedPreKey", reflect.TypeOf((*MockUserRepository)(nil).UpsertSignedPreKey), ctx, spk)
}

// UsernameExists mocks base method.
func (m *MockUserRepository) UsernameExists(ctx context.Context, username string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UsernameExists", ctx, username)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UsernameExists indicates an expected call of UsernameExists.
func (mr *MockUserRepositoryMockRecorder) UsernameExists(ctx, username interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UsernameExists", reflect.TypeOf((*MockUserRepository)(nil).UsernameExists), ctx, username)
}
